import type { CelestialObject, ISSPosition, VisibleObject } from '@/types'

export const SAMPLE_VISIBLE_OBJECTS: VisibleObject[] = [
  {
    id: 'obj-1',
    name: 'Jupiter',
    type: 'planet',
    magnitude: -2.1,
    altitude: 42,
    azimuth: 185,
    visible: true,
    riseTime: '2026-06-23T18:45:00.000Z',
    setTime: '2026-06-24T04:30:00.000Z',
    peakAltitude: 48,
    description: 'The largest planet in our solar system, visible as a bright point in the evening sky.',
  },
  {
    id: 'obj-2',
    name: 'Saturn',
    type: 'planet',
    magnitude: 0.6,
    altitude: 28,
    azimuth: 210,
    visible: true,
    riseTime: '2026-06-23T20:10:00.000Z',
    setTime: '2026-06-24T06:00:00.000Z',
    peakAltitude: 35,
    description: 'Known for its spectacular ring system, best viewed through a telescope.',
  },
  {
    id: 'obj-3',
    name: 'Vega',
    type: 'star',
    magnitude: 0.0,
    altitude: 78,
    azimuth: 45,
    visible: true,
    riseTime: '2026-06-23T14:00:00.000Z',
    setTime: '2026-06-24T02:00:00.000Z',
    peakAltitude: 85,
    description: 'One of the brightest stars in the northern hemisphere, part of the Summer Triangle.',
  },
  {
    id: 'obj-4',
    name: 'Andromeda Galaxy',
    type: 'galaxy',
    magnitude: 3.4,
    altitude: 55,
    azimuth: 310,
    visible: true,
    riseTime: '2026-06-23T22:00:00.000Z',
    setTime: '2026-06-24T08:00:00.000Z',
    peakAltitude: 62,
    description: 'The nearest major galaxy to the Milky Way, visible to the naked eye under dark skies.',
  },
  {
    id: 'obj-5',
    name: 'Orion Nebula',
    type: 'nebula',
    magnitude: 4.0,
    altitude: -5,
    azimuth: 120,
    visible: false,
    riseTime: '2026-06-24T03:00:00.000Z',
    setTime: '2026-06-24T12:00:00.000Z',
    peakAltitude: 45,
    description: 'A stellar nursery located in the constellation Orion.',
  },
]

export const SAMPLE_RADAR_OBJECTS: CelestialObject[] = [
  ...SAMPLE_VISIBLE_OBJECTS,
  {
    id: 'obj-6',
    name: 'Mars',
    type: 'planet',
    magnitude: 1.2,
    altitude: 15,
    azimuth: 240,
    visible: true,
    description: 'The Red Planet, currently low on the southwestern horizon.',
  },
  {
    id: 'obj-7',
    name: 'ISS',
    type: 'satellite',
    magnitude: -3.5,
    altitude: 62,
    azimuth: 90,
    visible: true,
    description: 'International Space Station passing overhead.',
  },
  {
    id: 'obj-8',
    name: 'Polaris',
    type: 'star',
    magnitude: 2.0,
    altitude: 37,
    azimuth: 0,
    visible: true,
    description: 'The North Star, used for celestial navigation for centuries.',
  },
]

export const SAMPLE_ISS_POSITION: ISSPosition = {
  latitude: 42.356,
  longitude: -71.065,
  altitude: 408,
  velocity: 27600,
  timestamp: new Date().toISOString(),
  visibility: 'visible',
}
